#!/bin/bash

#Debian - Ubuntu Gaming Dependencies

DEPENDENCIES="libasound2-plugins:i386 libsdl2-2.0-0:i386 libdbus-1-3:i386 libsqlite3-0:i386"
CODECS="gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad:i386 gstreamer1.0-plugins-base:i386 gstreamer1.0-plugins-good:i386 gstreamer1.0-plugins-ugly:i386 gstreamer1.0-libav gstreamer1.0-libav:i386 gstreamer1.0-vaapi"
GLVK="libvulkan1 libvulkan1:i386 libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386 libgl1 libgl1:i386 intel-media-va-driver intel-media-va-driver:i386 mesa-utils mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers vainfo vulkan-tools mesa-va-drivers:i386 mesa-vdpau-drivers:i386 mesa-vulkan-drivers:i386"

sudo dpkg --add-architecture i386
sudo apt update
sudo apt install --install-recommends $GLVK $DEPENDENCIES $CODECS -y
